default:
  machines: 1000
  
local_test: 
  dgp_path: "./data/DGP_local_test.rds"
  machines: 1
  reps: 5
  nobs: 100
  method: "bart"
  signature: "local_test"

gcomp_asymp: 
  dgp_path: "./data/DGP_5000_5bin_BiasUniform_PosUniform.rds"
  reps: 1
  nobs: 100000
  method: "gcomp"
  signature: "gcomp_asymp_DGP_5000_5bin_BiasUniform_PosUniform"

ptmle_asymp: 
  dgp_path: "./data/DGP_5000_5bin_BiasUniform_PosUniform.rds"
  reps: 1
  nobs: 100000
  method: "ptmle"
  signature: "ptmle_asymp_DGP_5000_5bin_BiasUniform_PosUniform"

tmle_asymp: 
  dgp_path: "./data/DGP_5000_5bin_BiasUniform_PosUniform.rds"
  reps: 1
  nobs: 100000
  method: "tmle"
  signature: "tmle_asymp_DGP_5000_5bin_BiasUniform_PosUniform"
  
bart_asymp: 
  dgp_path: "./data/DGP_5000_5bin_BiasUniform_PosUniform.rds"
  reps: 1
  nobs: 100000
  method: "bart"
  signature: "bart_asymp_DGP_5000_5bin_BiasUniform_PosUniform"

gcomp_1000: 
  dgp_path: "./data/DGP_5000_5bin_BiasUniform_PosUniform.rds"
  reps: 500
  nobs: 1000
  method: "gcomp"
  signature: "gcomp_1000_DGP_5000_5bin_BiasUniform_PosUniform"

gcomp_250: 
  dgp_path: "./data/DGP_5000_5bin_BiasUniform_PosUniform.rds"
  reps: 500
  nobs: 250
  method: "gcomp"
  signature: "gcomp_250_DGP_5000_5bin_BiasUniform_PosUniform"

ptmle_1000: 
  dgp_path: "./data/DGP_5000_5bin_BiasUniform_PosUniform.rds"
  reps: 500
  nobs: 1000
  method: "ptmle"
  signature: "ptmle_1000_DGP_5000_5bin_BiasUniform_PosUniform"

ptmle_250: 
  dgp_path: "./data/DGP_5000_5bin_BiasUniform_PosUniform.rds"
  reps: 500
  nobs: 250
  method: "ptmle"
  signature: "ptmle_250_DGP_5000_5bin_BiasUniform_PosUniform"

tmle_1000: 
  dgp_path: "./data/DGP_5000_5bin_BiasUniform_PosUniform.rds"
  reps: 500
  nobs: 1000
  method: "tmle"
  signature: "tmle_1000_DGP_5000_5bin_BiasUniform_PosUniform"

tmle_250: 
  dgp_path: "./data/DGP_5000_5bin_BiasUniform_PosUniform.rds"
  reps: 500
  nobs: 250
  method: "tmle"
  signature: "tmle_250_DGP_5000_5bin_BiasUniform_PosUniform"

bart_1000: 
  dgp_path: "./data/DGP_5000_5bin_BiasUniform_PosUniform.rds"
  reps: 500
  nobs: 1000
  method: "bart"
  signature: "bart_1000_DGP_5000_5bin_BiasUniform_PosUniform"
  
bart_250: 
  dgp_path: "./data/DGP_5000_5bin_BiasUniform_PosUniform.rds"
  reps: 500
  nobs: 250
  method: "bart"
  signature: "bart_250_DGP_5000_5bin_BiasUniform_PosUniform"
